name: Build and Test

on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        branches:
            - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Upgrade setuptools, pip and wheel
        run: python -m pip install -U setuptools pip wheel
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: python -m tox -e "py,coverage"
        env:
          PYTEST_ADDOPTS: --color=yes
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        with:
          files: .tox/coverage.xml
